project:
  type: website

website:
  title: "Muhammad Al Hasib"

  navbar:
    left:
      - text: Home
        href: index.qmd
        
      - text: About
        href: about.qmd
        
      - text: Research
        href: research.qmd

      - text: CV
        href: cv.qmd
        
      - text: Coursework
        href: coursework.qmd

      - text: EPPS 6323 Assignments
        href: assignments.qmd

  page-footer:
    center: "© 2026 Muhammad Al Hasib"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true