---
title: "About Me"
---

I am a PhD student in Public and Nonprofit Management, driven by a deep interest in research, policy analysis, and public management. My academic journey has been shaped by a passion for understanding complex governance systems, the impact of public policy, and the relationship between institutions and the people they serve.

Currently, I work as a Teaching Assistant and actively contribute to the research areas of education policy, social equity, behavioral public administration, and social welfare. I am particularly interested in using evidence-based approaches to evaluate programs and design inclusive, effective policies.

My professional experience spans from BRAC University and Stanford University to Oxfam GB. Also, my experience encompasses academic writing, data analysis, and cross-cultural collaboration. I’m also committed to mentoring students and contributing to an engaged educational environment.

I welcome connections and conversations around research collaboration, program and policy development, and consulting opportunities.